{
  "definitions": {
    "propertyList": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "property-reference": {
          "comment": "property-reference is an extension to the JSON schema validator. Here it jumps to the root level of the hierarchy and tests if a value is an existing key there (i.e a defined property). See test/validate-schema.js for implementation details.",
          "$data": "/"
        }
      }
    },
    "animationType": {
      "enum": [
        "angleBasicShapeOrPath",
        "angleOrBasicShapeOrPath",
        "basicShapeOtherwiseNo",
        "byComputedValueType",
        "color",
        "discrete",
        "eachOfShorthandPropertiesExceptUnicodeBiDiAndDirection",
        "filterList",
        "fontStretch",
        "fontWeight",
        "integer",
        "length",
        "lpc",
        "notAnimatable",
        "numberOrLength",
        "number",
        "position",
        "rectangle",
        "repeatableListOfSimpleListOfLpc",
        "shadowList",
        "simpleListOfLpc",
        "simpleListOfLpcDifferenceLpc",
        "transform",
        "visibility"
      ]
    },
    "percentages": {
      "enum": [
        "blockSizeOfContainingBlock",
        "dependsOnLayoutModel",
        "inlineSizeOfContainingBlock",
        "lengthsAsPercentages",
        "logicalHeightOfContainingBlock",
        "logicalWidthOfContainingBlock",
        "maxZoomFactor",
        "minZoomFactor",
        "no",
        "referToBorderBox",
        "referToContainingBlockHeight",
        "referToDimensionOfBorderBox",
        "referToDimensionOfContentArea",
        "referToElementFontSize",
        "referToFlexContainersInnerMainSize",
        "referToHeightOfBackgroundPositioningAreaMinusBackgroundImageHeight",
        "referToLineBoxWidth",
        "referToLineHeight",
        "referToParentElementsFontSize",
        "referToSizeOfBackgroundPositioningAreaMinusBackgroundImageSize",
        "referToSizeOfBorderImage",
        "referToSizeOfBoundingBox",
        "referToSizeOfContainingBlock",
        "referToSizeOfElement",
        "referToSizeOfFont",
        "referToSizeOfMaskBorderImage",
        "referToSizeOfMaskPaintingArea",
        "referToTotalPathLength",
        "referToWidthAndHeightOfElement",
        "referToWidthOfAffectedGlyph",
        "referToWidthOfBackgroundPositioningAreaMinusBackgroundImageHeight",
        "referToWidthOfContainingBlock",
        "referToWidthOrHeightOfBorderImageArea",
        "referToReferenceBoxWhenSpecifiedOtherwiseBorderBox",
        "regardingHeightOfGeneratedBoxContainingBlockPercentages0",
        "regardingHeightOfGeneratedBoxContainingBlockPercentagesNone",
        "regardingHeightOfGeneratedBoxContainingBlockPercentagesRelativeToContainingBlock",
        "relativeToBackgroundPositioningArea",
        "relativeToMaskBorderImageArea",
        "relativeToScrollContainerPaddingBoxAxis",
        "relativeToTheScrollContainersScrollport",
        "relativeToWidthAndHeight"
      ]
    },
    "computed": {
      "enum": [
        "absoluteLength",
        "absoluteLength0ForNone",
        "absoluteLength0IfColumnRuleStyleNoneOrHidden",
        "absoluteLengthOr0IfBorderBottomStyleNoneOrHidden",
        "absoluteLengthOr0IfBorderLeftStyleNoneOrHidden",
        "absoluteLengthOr0IfBorderRightStyleNoneOrHidden",
        "absoluteLengthOr0IfBorderTopStyleNoneOrHidden",
        "absoluteLengthOrAsSpecified",
        "absoluteLengthOrKeyword",
        "absoluteLengthOrNone",
        "absoluteLengthOrNormal",
        "absoluteLengthOrPercentage",
        "absoluteLengthsSpecifiedColorAsSpecified",
        "absoluteLengthZeroIfBorderStyleNoneOrHidden",
        "absoluteLengthZeroOrLarger",
        "absoluteURIOrNone",
        "angleRoundedToNextQuarter",
        "asAutoOrColor",
        "asDefinedForBasicShapeWithAbsoluteURIOtherwiseAsSpecified",
        "asLength",
        "asSpecified",
        "asSpecifiedAppliesToEachProperty",
        "asSpecifiedButVisibleOrClipReplacedToAutoOrHiddenIfOtherValueDifferent",
        "asSpecifiedExceptMatchParent",
        "asSpecifiedExceptPositionedFloatingAndRootElementsKeywordMaybeDifferent",
        "asSpecifiedRelativeToAbsoluteLengths",
        "asSpecifiedURLsAbsolute",
        "asSpecifiedWithExceptionOfResolution",
        "asSpecifiedWithLengthsAbsoluteAndNormalComputingToZeroExceptMultiColumn",
        "asSpecifiedWithVarsSubstituted",
        "autoOnAbsolutelyPositionedElementsValueOfAlignItemsOnParent",
        "autoOrRectangle",
        "colorPlusThreeAbsoluteLengths",
        "computedColor",
        "consistsOfTwoDimensionKeywords",
        "consistsOfTwoKeywordsForOriginAndOffsets",
        "forLengthAbsoluteValueOtherwisePercentage",
        "invertForTranslucentColorRGBAOtherwiseRGB",
        "keywordOrNumericalValueBolderLighterTransformedToRealValue",
        "keywordPlusIntegerIfDigits",
        "lengthAbsolutePercentageAsSpecifiedOtherwiseAuto",
        "listEachItemConsistingOfAbsoluteLengthPercentageAndOrigin",
        "listEachItemHasTwoKeywordsOnePerDimension",
        "listEachItemTwoKeywordsOriginOffsets",
        "noneOrImageWithAbsoluteURI",
        "normalizedAngle",
        "normalOnElementsForPseudosNoneAbsoluteURIStringOrAsSpecified",
        "oneToFourPercentagesOrAbsoluteLengthsPlusFill",
        "optimumMinAndMaxValueOfAbsoluteLengthPercentageOrNormal",
        "optimumValueOfAbsoluteLengthOrNormal",
        "percentageAsSpecifiedAbsoluteLengthOrNone",
        "percentageAsSpecifiedOrAbsoluteLength",
        "percentageAutoOrAbsoluteLength",
        "percentageOrAbsoluteLengthPlusKeywords",
        "sameAsBoxOffsets",
        "sameAsMaxWidthAndMaxHeight",
        "sameAsMinWidthAndMinHeight",
        "sa