сть", "city": "Баган", "operator": "", "desc": "" },
	{ "mask": "+7(38354)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Довольное", "operator": "", "desc": "" },
	{ "mask": "+7(38355)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Карасук", "operator": "", "desc": "" },
	{ "mask": "+7(38356)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Кочки", "operator": "", "desc": "" },
	{ "mask": "+7(38357)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Краснозерское", "operator": "", "desc": "" },
	{ "mask": "+7(38358)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Купино", "operator": "", "desc": "" },
	{ "mask": "+7(38359)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Ордынское", "operator": "", "desc": "" },
	{ "mask": "+7(38360)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Северное", "operator": "", "desc": "" },
	{ "mask": "+7(38361)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Барабинск", "operator": "", "desc": "" },
	{ "mask": "+7(38362)#-##-##", "cc": "RU", "cd": "Russia", "region": "Новосибирская область", "city": "Куйбышев", "operator": "", "desc": "" },
	