Russia", "region": "Якутия", "city": "Оленёк", "operator": "", "desc": "" },
	{ "mask": "+7(413)###-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(4132)##-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Магадан", "operator": "", "desc": "" },
	{ "mask": "+7(41341)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Ола", "operator": "", "desc": "" },
	{ "mask": "+7(41342)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Палатка", "operator": "", "desc": "" },
	{ "mask": "+7(41343)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Ягодное", "operator": "", "desc": "" },
	{ "mask": "+7(41344)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Усть-Омчуг", "operator": "", "desc": "" },
	{ "mask": "+7(41345)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Сусуман", "operator": "", "desc": "" },
	{ "mask": "+7(41346)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Омсукчан", "operator": "", "desc": "" },
	{ "mask": "+7(41347)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Сеймчан", "operator": "", "desc": "" },
	{ "mask": "+7(41348)#-##-##", "cc": "RU", "cd": "Russia", "region": "Магаданская область", "city": "Эвен�