 "" },
	{ "mask": "+7(48153)#-##-##", "cc": "RU", "cd": "Russia", "region": "Смоленская область", "city": "Десногорск", "operator": "", "desc": "" },
	{ "mask": "+7(48155)#-##-##", "cc": "RU", "cd": "Russia", "region": "Смоленская область", "city": "Ершичи", "operator": "", "desc": "" },
	{ "mask": "+7(48165)#-##-##", "cc": "RU", "cd": "Russia", "region": "Смоленская область", "city": "Глинка", "operator": "", "desc": "" },
	{ "mask": "+7(48166)#-##-##", "cc": "RU", "cd": "Russia", "region": "Смоленская область", "city": "Духовщина", "operator": "", "desc": "" },
	{ "mask": "+7(48167)#-##-##", "cc": "RU", "cd": "Russia", "region": "Смоленская область", "city": "Кардымово", "operator": "", "desc": "" },
	{ "mask": "+7(482)###-##-##", "cc": "RU", "cd": "Russia", "region": "Тверская область", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(4822)##-##-##", "cc": "RU", "cd": "Russia", "region": "Тверская область", "city": "Тверь", "operator": "", "desc": "" },
	{ "mask": "+7(48230)#-##-##", "cc": "RU", "cd": "Russia", "region": "Тверская область", "city": "Пено", "operator": "", "desc": "" },
	{ "mask": "+7(48231)#-##-##", "cc": "RU", "cd": "Russia", "region": "Тверская область", "city": "Бежецк", "operator": "", "desc": "" },
	{ "mask": "+7(48232)#-##-##", "cc": "RU", "cd": "Russia", "region": "Тверская область", "city": "Ржев", "operator": "", "desc": "" },
	{ "mask": "+7(48233)#-##-##", "cc"