 "city": "Чусовой", "operator": "", "desc": "" },
	{ "mask": "+7(34257)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Большая Соснова", "operator": "", "desc": "" },
	{ "mask": "+7(34258)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Орда", "operator": "", "desc": "" },
	{ "mask": "+7(34259)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Уинское", "operator": "", "desc": "" },
	{ "mask": "+7(34260)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Кудымкар", "operator": "", "desc": "" },
	{ "mask": "+7(34261)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Чернушка", "operator": "", "desc": "" },
	{ "mask": "+7(34262)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Куеда", "operator": "", "desc": "" },
	{ "mask": "+7(34263)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Звёздный", "operator": "", "desc": "" },
	{ "mask": "+7(34265)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Добрянка", "operator": "", "desc": "" },
	{ "mask": "+7(34266)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Октябрьский", "operator": "", "desc": "" },
	{ "mask": "+7(34268)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Частые", "operator": "", "desc": "" },
	{ "mask": "+7(34269)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Горнозаводск", "operator": "", "desc": "" },
	{ "mask": "+7(34271)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Кунгур", "operator": "", "desc": "" },
	{ "mask": "+7(34272)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Нытва", "operator": "", "desc": "" },
	{ "mask": "+7(34273)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Краснокамск", "operator": "", "desc": "" },
	{ "mask": "+7(34274)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Александровск", "operator": "", "desc": "" },
	{ "mask": "+7(34275)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Суксун", "operator": "", "desc": "" },
	{ "mask": "+7(34276)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Ильинский", "operator": "", "desc": "" },
	{ "mask": "+7(34277)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Сива", "operator": "", "desc": "" },
	{ "mask": "+7(34278)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Очер", "operator": "", "desc": "" },
	{ "mask": "+7(34279)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Оханск", "operator": "", "desc": "" },
	{ "mask": "+7(34291)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Оса", "operator": "", "desc": "" },
	{ "mask": "+7(34292)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Барда", "operator": "", "desc": "" },
	{ "mask": "+7(34293)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Кочёво", "operator": "", "desc": "" },
	{ "mask": "+7(34294)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Юрла", "operator": "", "desc": "" },
	{ "mask": "+7(34296)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Елово", "operator": "", "desc": "" },
	{ "mask": "+7(34297)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Карагай", "operator": "", "desc": "" },
	{ "mask": "+7(34298)#-##-##", "cc": "RU", "cd": "Russia", "region": "Пермский край", "city": "Коса", "operator": "", "desc": "" },
	{ "mask": "+7(343)###-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(343)2##-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Екатеринбург", "operator": "", "desc": "" },
	{ "mask": "+7(343)3##-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Екатеринбург", "operator": "", "desc": "" },
	{ "mask": "+7(34341)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Качканар", "operator": "", "desc": "" },
	{ "mask": "+7(34342)2-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Нижняя Тура", "operator": "", "desc": "" },
	{ "mask": "+7(34342)3-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Лесной", "operator": "", "desc": "" },
	{ "mask": "+7(34342)5-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Лесной", "operator": "", "desc": "" },
	{ "mask": "+7(34342)6-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Лесной", "operator": "", "desc": "" },
	{ "mask": "+7(34343)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Красноуральск", "operator": "", "desc": "" },
	{ "mask": "+7(34344)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Кушва", "operator": "", "desc": "" },
	{ "mask": "+7(34345)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Верхняя Салда", "operator": "", "desc": "" },
	{ "mask": "+7(34346)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Алапаевск", "operator": "", "desc": "" },
	{ "mask": "+7(34347)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Таборы", "operator": "", "desc": "" },
	{ "mask": "+7(34349)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Туринск", "operator": "", "desc": "" },
	{ "mask": "+7(3435)##-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Нижний Тагил", "operator": "", "desc": "" },
	{ "mask": "+7(34350)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Полевской", "operator": "", "desc": "" },
	{ "mask": "+7(34355)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Ирбит", "operator": "", "desc": "" },
	{ "mask": "+7(34356)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Невьянск", "operator": "", "desc": "" },
	{ "mask": "+7(34357)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Кировград", "operator": "", "desc": "" },
	{ "mask": "+7(34358)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Шаля", "operator": "", "desc": "" },
	{ "mask": "+7(34360)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Тавда", "operator": "", "desc": "" },
	{ "mask": "+7(34361)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Туринская Слобода", "operator": "", "desc": "" },
	{ "mask": "+7(34362)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Байкалово", "operator": "", "desc": "" },
	{ "mask": "+7(34363)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Артемовский", "operator": "", "desc": "" },
	{ "mask": "+7(34364)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Реж", "operator": "", "desc": "" },
	{ "mask": "+7(34365)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Асбест", "operator": "", "desc": "" },
	{ "mask": "+7(34367)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Тугулым", "operator": "", "desc": "" },
	{ "mask": "+7(34368)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Верхняя Пышма", "operator": "", "desc": "" },
	{ "mask": "+7(34369)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Берёзовский", "operator": "", "desc": "" },
	{ "mask": "+7(34370)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Новоуральск", "operator": "", "desc": "" },
	{ "mask": "+7(34371)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Талица", "operator": "", "desc": "" },
	{ "mask": "+7(34372)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Пышма", "operator": "", "desc": "" },
	{ "mask": "+7(34373)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Сухой Лог", "operator": "", "desc": "" },
	{ "mask": "+7(34374)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Сысерть", "operator": "", "desc": "" },
	{ "mask": "+7(34375)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Камышлов", "operator": "", "desc": "" },
	{ "mask": "+7(34376)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Богданович", "operator": "", "desc": "" },
	{ "mask": "+7(34377)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Белоярский", "operator": "", "desc": "" },
	{ "mask": "+7(34380)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Североуральск", "operator": "", "desc": "" },
	{ "mask": "+7(34383)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Карпинск", "operator": "", "desc": "" },
	{ "mask": "+7(34383)5-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Волчанск", "operator": "", "desc": "" },
	{ "mask": "+7(34384)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Краснотурьинск", "operator": "", "desc": "" },
	{ "mask": "+7(34385)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Серов", "operator": "", "desc": "" },
	{ "mask": "+7(34386)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Ивдель", "operator": "", "desc": "" },
	{ "mask": "+7(34387)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Гари", "operator": "", "desc": "" },
	{ "mask": "+7(34388)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Новая Ляля", "operator": "", "desc": "" },
	{ "mask": "+7(34389)#-##-##", "cc": "RU", "cd": "Russia", "region": "Свердловская область", "city": "Верхотурье", "operator": "", "desc": "" },
	{ "mask": "+7(3439)2#-##-##", "