"region": "Алтайский край", "city": "Кытманово", "operator": "", "desc": "" },
	{ "mask": "+7(38591)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Тальменка", "operator": "", "desc": "" },
	{ "mask": "+7(38592)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Залесово", "operator": "", "desc": "" },
	{ "mask": "+7(38593)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Ельцовка", "operator": "", "desc": "" },
	{ "mask": "+7(38594)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Солонешное", "operator": "", "desc": "" },
	{ "mask": "+7(38595)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Заринск", "operator": "", "desc": "" },
	{ "mask": "+7(38596)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Целинное", "operator": "", "desc": "" },
	{ "mask": "+7(38597)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Тогул", "operator": "", "desc": "" },
	{ "mask": "+7(38598)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Советское", "operator": "", "desc": "" },
	{ "mask": "+7(38599)#-##-##", "cc": "RU", "cd": "Russia", "region": "Алтайский край", "city": "Усть-Калманка", "operator": "", "desc": "" },
	{ "mask": "+7(388)###-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(3882)##-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Горно-Алтайск", "operator": "", "desc": "" },
	{ "mask": "+7(38840)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Чоя", "operator": "", "desc": "" },
	{ "mask": "+7(38841)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Чемал", "operator": "", "desc": "" },
	{ "mask": "+7(38842)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Кош-Агач", "operator": "", "desc": "" },
	{ "mask": "+7(38843)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Турочак", "operator": "", "desc": "" },
	{ "mask": "+7(38844)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Майма", "operator": "", "desc": "" },
	{ "mask": "+7(38845)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Онгудай", "operator": "", "desc": "" },
	{ "mask": "+7(38846)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Акташ", "operator": "", "desc": "" },
	{ "mask": "+7(38847)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Усть-Кан", "operator": "", "desc": "" },
	{ "mask": "+7(38848)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Усть-Кокса", "operator": "", "desc": "" },
	{ "mask": "+7(38849)#-##-##", "cc": "RU", "cd": "Russia", "region": "Республика Алтай", "city": "Шебалино", "operator": "", "desc": "" },
	{ "mask": "+7(390)###-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(3902)##-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Абакан", "operator": "", "desc": "" },
	{ "mask": "+7(39031)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Черногорск", "operator": "", "desc": "" },
	{ "mask": "+7(39032)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Усть-Абакан", "operator": "", "desc": "" },
	{ "mask": "+7(39033)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Сорск", "operator": "", "desc": "" },
	{ "mask": "+7(39034)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Боград", "operator": "", "desc": "" },
	{ "mask": "+7(39035)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Шира", "operator": "", "desc": "" },
	{ "mask": "+7(39036)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Копьёво", "operator": "", "desc": "" },
	{ "mask": "+7(39041)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Белый Яр", "operator": "", "desc": "" },
	{ "mask": "+7(39042)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Саяногорск", "operator": "", "desc": "" },
	{ "mask": "+7(39044)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Бея", "operator": "", "desc": "" },
	{ "mask": "+7(39045)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Аскиз", "operator": "", "desc": "" },
	{ "mask": "+7(39046)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Таштып", "operator": "", "desc": "" },
	{ "mask": "+7(39047)#-##-##", "cc": "RU", "cd": "Russia", "region": "Хакасия", "city": "Абаза", "operator": "", "desc": "" },
	{ "mask": "+7(391)###-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(391)2##-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Красноярск", "operator": "", "desc": "" },
	{ "mask": "+7(39131)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Сосновоборск", "operator": "", "desc": "" },
	{ "mask": "+7(39132)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Минусинск", "operator": "", "desc": "" },
	{ "mask": "+7(39133)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Емельяново", "operator": "", "desc": "" },
	{ "mask": "+7(39134)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Краснотуранск", "operator": "", "desc": "" },
	{ "mask": "+7(39135)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Идринское", "operator": "", "desc": "" },
	{ "mask": "+7(39136)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Курагино", "operator": "", "desc": "" },
	{ "mask": "+7(39137)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Каратузское", "operator": "", "desc": "" },
	{ "mask": "+7(39138)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Ермаковское", "operator": "", "desc": "" },
	{ "mask": "+7(39139)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Шушенское", "operator": "", "desc": "" },
	{ "mask": "+7(39140)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Партизанское", "operator": "", "desc": "" },
	{ "mask": "+7(39141)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Мотыгино", "operator": "", "desc": "" },
	{ "mask": "+7(39142)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Агинское", "operator": "", "desc": "" },
	{ "mask": "+7(39143)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Кодинск", "operator": "", "desc": "" },
	{ "mask": "+7(39144)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Дивногорск", "operator": "", "desc": "" },
	{ "mask": "+7(39145)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Лесосибирск", "operator": "", "desc": "" },
	{ "mask": "+7(39146)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Уяр", "operator": "", "desc": "" },
	{ "mask": "+7(39147)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Новоселово", "operator": "", "desc": "" },
	{ "mask": "+7(39148)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Балахта", "operator": "", "desc": "" },
	{ "mask": "+7(39149)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Шалинское", "operator": "", "desc": "" },
	{ "mask": "+7(39150)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Новобирилюссы", "operator": "", "desc": "" },
	{ "mask": "+7(39151)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Ачинск", "operator": "", "desc": "" },
	{ "mask": "+7(39152)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Диксон", "operator": "", "desc": "" },
	{ "mask": "+7(39153)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Шарыпово", "operator": "", "desc": "" },
	{ "mask": "+7(39154)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Козулька", "operator": "", "desc": "" },
	{ "mask": "+7(39155)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Назарово", "operator": "", "desc": "" },
	{ "mask": "+7(39156)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Ужур", "operator": "", "desc": "" },
	{ "mask": "+7(39157)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Боготол", "operator": "", "desc": "" },
	{ "mask": "+7(39158)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Тюхтет", "operator": "", "desc": "" },
	{ "mask": "+7(39159)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Большой Улуй", "operator": "", "desc": "" },
	{ "mask": "+7(39160)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Северо-Енисейский", "operator": "", "desc": "" },
	{ "mask": "+7(39161)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Канск", "operator": "", "desc": "" },
	{ "mask": "+7(39162)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Богучаны", "operator": "", "desc": "" },
	{ "mask": "+7(39163)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Абан", "operator": "", "desc": "" },
	{ "mask": "+7(39164)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Тасеево", "operator": "", "desc": "" },
	{ "mask": "+7(39165)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Заозерный", "operator": "", "desc": "" },
	{ "mask": "+7(39166)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Пировское", "operator": "", "desc": "" },
	{ "mask": "+7(39167)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Дзержинское", "operator": "", "desc": "" },
	{ "mask": "+7(39168)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Бородино", "operator": "", "desc": "" },
	{ "mask": "+7(39169)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Зеленогорск", "operator": "", "desc": "" },
	{ "mask": "+7(39170)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Тура", "operator": "", "desc": "" },
	{ "mask": "+7(39171)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Нижний Ингаш", "operator": "", "desc": "" },
	{ "mask": "+7(39172)#-##-##", "cc": "RU", "cd": "Russia", "region": "Красноярский край", "city": "Игарка", "operator": "", "desc": "" },
	{ "mask": "+7(39173)#-##-##