 "mask": "+7(42362)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Анучино", "operator": "", "desc": "" },
	{ "mask": "+7(42363)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Партизанск", "operator": "", "desc": "" },
	{ "mask": "+7(42365)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Владимиро-Александровское", "operator": "", "desc": "" },
	{ "mask": "+7(42371)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Яковлевка", "operator": "", "desc": "" },
	{ "mask": "+7(42372)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Чугуевка", "operator": "", "desc": "" },
	{ "mask": "+7(42373)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Дальнегорск", "operator": "", "desc": "" },
	{ "mask": "+7(42374)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Терней", "operator": "", "desc": "" },
	{ "mask": "+7(42375)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Кавалерово", "operator": "", "desc": "" },
	{ "mask": "+7(42376)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Ольга", "operator": "", "desc": "" },
	{ "mask": "+7(42377)#-##-##", "cc": "RU", "cd": "Russia", "region": "Приморский край", "city": "Лазо", "operator": "", "desc": "" },
	{ "mask": "+7(424)###-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(4242)##-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Южно-Сахалинск", "operator": "", "desc": "" },
	{ "mask": "+7(42431)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Поронайск", "operator": "", "desc": "" },
	{ "mask": "+7(42432)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Углегорск", "operator": "", "desc": "" },
	{ "mask": "+7(42433)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Холмск", "operator": "", "desc": "" },
	{ "mask": "+7(42434)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Александровск-Сахалинский", "operator": "", "desc": "" },
	{ "mask": "+7(42435)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Корсаков", "operator": "", "desc": "" },
	{ "mask": "+7(42436)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Невельск", "operator": "", "desc": "" },
	{ "mask": "+7(42437)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Оха", "operator": "", "desc": "" },
	{ "mask": "+7(42441)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Анива", "operator": "", "desc": "" },
	{ "mask": "+7(42442)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Долинск", "operator": "", "desc": "" },
	{ "mask": "+7(42443)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Макаров", "operator": "", "desc": "" },
	{ "mask": "+7(42444)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Ноглики", "operator": "", "desc": "" },
	{ "mask": "+7(42446)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Томари", "operator": "", "desc": "" },
	{ "mask": "+7(42447)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Тымовское", "operator": "", "desc": "" },
	{ "mask": "+7(42452)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Смирных", "operator": "", "desc": "" },
	{ "mask": "+7(42453)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Северо-Курильск", "operator": "", "desc": "" },
	{ "mask": "+7(42454)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Курильск", "operator": "", "desc": "" },
	{ "mask": "+7(42455)#-##-##", "cc": "RU", "cd": "Russia", "region": "Сахалинская область", "city": "Южно-Курильск", "operator": "", "desc": "" },
	{ "mask": "+7(426)###-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(42622)#-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "Биробиджан", "operator": "", "desc": "" },
	{ "mask": "+7(42632)#-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "Смидович", "operator": "", "desc": "" },
	{ "mask": "+7(42663)#-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "Ленинское", "operator": "", "desc": "" },
	{ "mask": "+7(42665)#-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "Амурзет", "operator": "", "desc": "" },
	{ "mask": "+7(42666)#-##-##", "cc": "RU", "cd": "Russia", "region": "Еврейская автономная область", "city": "Облучье", "operator": "", "desc": "" },
	{ "mask": "+7(427)###-##-##", "cc": "RU", "cd": "Russia", "region": "Чукотский автономный округ", "city": "", "operator": "", "desc": "" },
	{ "mask": "+7(42722)#-##-##", "cc": "RU", "cd": "Russia", "region": "Чукотский автономный округ", "city": "Анадырь", "operator": "", "desc": "" },
	{ "mask": "+7(42732)#-##-##", "cc": "RU", "cd": "Russia", "region": "Чукотский автономный округ", "city": "Угольные Копи", "operator": "", "desc": "" },
	{ "mask": "+7(42733)#-##-##", "cc": "RU", "cd": "Russia", "region": "Чукотский автономный округ", "city": "Беринговский", "operator": "", "desc": "" },
	{ "mask": "+7(42734)#-##-##", "cc": "RU", "cd": "Russia", "region": "Чукотский автономный округ", "city": "Эгвекинот", "operator": "", "desc": "" },
	{ "mask": "+7(42735)#-##-##", "cc": "RU", "cd": "Russia", "region": 