key,a.mode),c.elementType=a.elementType,c.type=a.type,c.stateNode=a.stateNode,c.alternate=a,a.alternate=c):(c.pendingProps=b,c.type=a.type,c.flags=0,c.subtreeFlags=0,c.deletions=null,c.actualDuration=0,c.actualStartTime=-1);c.flags=a.flags&14680064;c.childLanes=a.childLanes;c.lanes=a.lanes;c.child=a.child;c.memoizedProps=a.memoizedProps;c.memoizedState=a.memoizedState;c.updateQueue=a.updateQueue;b=a.dependencies;c.dependencies=null===b?null:
{lanes:b.lanes,firstContext:b.firstContext};c.sibling=a.sibling;c.index=a.index;c.ref=a.ref;c.selfBaseDuration=a.selfBaseDuration;c.treeBaseDuration=a.treeBaseDuration;return c}
function Nh(a,b,c,d,e,f){var g=2;d=a;if("function"===typeof a)Fj(a)&&(g=1);else if("string"===typeof a)g=5;else a:switch(a){case ya:return Ph(c.children,e,f,b);case za:g=8;e|=8;break;case Aa:return a=Pg(12,c,b,e|2),a.elementType=Aa,a.lanes=f,a.stateNode={effectDuration:0,passiveEffectDuration:0},a;case Ea:return a=Pg(13,c,b,e),a.elementType=Ea,a.lanes=f,a;case Fa:return a=Pg(19,c,b,e),a.elementType=Fa,a.lanes=f,a;case Ia:return Wj(c,e,f,b);default:if("object"===typeof a&&null!==a)switch(a.$$typeof){case Ba:g=
10;break a;case Ca:g=9;break a;case Da:g=11;break a;case Ga:g=14;break a;case Ha:g=16;d=null;break a}throw Error(p(130,null==a?a:typeof a,""));}b=Pg(g,c,b,e);b.elementType=a;b.type=d;b.lanes=f;return b}function Ph(a,b,c,d){a=Pg(7,a,d,b);a.lanes=c;return a}function Wj(a,b,c,d){a=Pg(22,a,d,b);a.elementType=Ia;a.lanes=c;a.stateNode={isHidden:!1};return a}function Mh(a,b,c){a=Pg(6,a,null,b);a.lanes=c;return a}
function Oh(a,b,c){b=Pg(4,null!==a.children?a.children:[],a.key,b);b.lanes=c;b.stateNode={containerInfo:a.containerInfo,pendingChildren:null,implementation:a.implementation};return b}
function Pl(a,b,c,d,e){this.tag=b;this.containerInfo=a;this.finishedWork=this.pingCache=this.current=this.pendingChildren=null;this.timeoutHandle=-1;this.callbackNode=this.pendingContext=this.context=null;this.callbackPriority=0;this.eventTimes=Lc(0);this.expirationTimes=Lc(-1);this.entangledLanes=this.finishedLanes=this.mutableReadLanes=this.expiredLanes=this.pingedLanes=this.suspendedLanes=this.pendingLanes=0;this.entanglements=Lc(0);this.identifierPrefix=d;this.onRecoverableError=e;this.mutableSourceEagerHydrationData=
null;this.passiveEffectDuration=this.effectDuration=0;this.memoizedUpdaters=new Set;a=this.pendingUpdatersLaneMap=[];for(b=0;31>b;b++)a.push(new Set)}function Ql(a,b,c,d,e,f,g,h,k){a=new Pl(a,b,c,h,k);1===b?(b=1,!0===f&&(b|=8)):b=0;mc&&(b|=2);f=Pg(3,null,null,b);a.current=f;f.stateNode=a;f.memoizedState={element:d,isDehydrated:c,cache:null,transitions:null,pendingSuspenseBoundaries:null};oh(f);return a}
function Rl(a,b,c){var d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:null;return{$$typeof:xa,key:null==d?null:""+d,children:a,containerInfo:b,implementation:c}}
function Sl(a){if(!a)return ig;a=a._reactInternals;a:{if(Vb(a)!==a||1!==a.tag)throw Error(p(170));var b=a;do{switch(b.tag){case 3:b=b.stateNode.context;break a;case 1:if(mg(b.type)){b=b.stateNode.__reactInternalMemoizedMergedChildContext;break a}}b=b.return}while(null!==b);throw Error(p(171));}if(1===a.tag){var c=a.type;if(mg(c))return pg(a,c,b)}return b}
function Tl(a,b,c,d,e,f,g,h,k){a=Ql(c,d,!0,a,e,f,g,h,k);a.context=Sl(null);c=a.current;d=zh();e=Ah(c);f=qh(d,e);f.callback=void 0!==b&&null!==b?b:null;rh(c,f,e);a.current.lanes=e;Mc(a,e,d);ql(a,d);return a}
function Ul(a,b,c,d){var e=b.current,f=zh(),g=Ah(e);null!==B&&"funct